In [3]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, role):
        super().__init__(name, family, salary, department)
        self.role = role


emp1 = Employee("charan", "Family A", 60000, "LEAD")
emp2 = Employee("venkat", "Family B", 75000, "Engineering")
emp3 = Employee("phani", "Family C", 80000, "Marketing")

ft_emp1 = FulltimeEmployee("NAGA", "Family D", 90000, "Sales", "Manager")
ft_emp2 = FulltimeEmployee("HARSHA", "Family E", 85000, "IT", "Developer")

employees = [emp1, emp2, emp3, ft_emp1, ft_emp2]
avg_salary = Employee.average_salary(employees)

print("Number of employees:", Employee.employee_count)
print("Average salary:", avg_salary)


Number of employees: 5
Average salary: 78000.0


In [4]:
import numpy as np
random_vector = np.random.uniform(1, 20, 20)
reshaped_array = random_vector.reshape(4, 5)
reshaped_array[np.arange(reshaped_array.shape[0]), reshaped_array.argmax(axis=1)] = 0
print(reshaped_array)


[[ 0.          7.96133423 11.01167088 11.41322144  1.92358388]
 [14.64722696  0.         14.60663651  1.35024343 14.77316063]
 [ 0.          2.28721675  9.51760402  6.634337    3.19968217]
 [ 0.         14.8337744   5.43368534 10.0189228   6.62714128]]
